### PR TITLE
ORC-1101: [C++] Improve malformed STRUCT handling

### LINKED ISSUE #1021: ORC Format Parsing – Out-of-Bounds Access in Protobuf Messages
what happens if type.fieldnames_size()  is less than the type.subtypes_size(). The type.fieldnames(i) will be invalid access. 

File name :  TypeImpl.cc
```
case proto::Type_Kind_STRUCT: {
TypeImpl* result = new TypeImplSTRUCT);
uint64_t size = static_cast<uint64_t>(type.subtypes_size());
std::vector<Type*> typeList(size);
std::vector<std::string> fieldList(size);
for(int i=0; i < type.subtypes_size(); ++i)
{ result->addStructField(type.fieldnames(i), convertType(footer.types(static_cast<int> (type.subtypes(i))),footer)); }
return std::unique_ptr<Type>(result);
```
I reproduced the scenario by modifying c++/test/TestType.cc (refer screenshot) and it crashed.(refer output screenshot
Screen Shot 2022-01-19 at 12 33 21 PM
)

Screen Shot 2022-01-19 at 12 32 29 PM

### PR DESCRIPTION
**Pull request by HeenaBansal2009**
### What changes were proposed in this pull request?

The changes are made to validate the indices in the Protobuf message type tree especially for the Type_Kind_STRUCT when fieldnames are less than the subtypes_size() , so it won't crash when we convert the proto::Types to TypeImpls.

### Why are the changes needed?

To handle the malformed STRUCT type more gracefully.

### How was this patch tested?

Pass the CIs with the newly added test coverage.

Closes #1021 and #1023

### CODE REVIEW

File: c++/src/TypeImpl.cc [hunk 1]
```diff
@@ -413,6 +413,8 @@ namespace orc {
   std::unique_ptr<Type> convertType(const proto::Type& type,
                                     const proto::Footer& footer) {
     std::unique_ptr<Type> ret;
+    //check for corrupt footers before conversion
+    checkProtoTypes(footer);
```
Comment (dongjoon-hyun) [inline c++/src/TypeImpl.cc:417]: Could you describe what happens after this PR? Previously, you filed an issue with `it crashed`.

Comment (HeenaBansal2009) [reply c++/src/TypeImpl.cc:417]: > Could you describe what happens after this PR? Previously, you filed the issue with `it crashed`.

@dongjoon-hyun , Thanks for reviewing the PR. I can update as below : 

// Validate the indices in the Protobuf message type tree especially for the Type_Kind_STRUCT when fieldnames are less than the subtypes_size() , so we won't crash when we convert the proto::Types to TypeImpls.

Comment (dongjoon-hyun) [reply c++/src/TypeImpl.cc:417]: Please put it into the PR description instead of commenting here.
The PR description will be a commit message later.

Comment (HeenaBansal2009) [reply c++/src/TypeImpl.cc:417]: Done.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
It seems that we have a related test coverage for that, @HeenaBansal2009 .

https://github.com/apache/orc/blob/89af2cbe53fe4e53c948a4c389bdd14da3303687/c%2B%2B/test/TestType.cc#L381-L407

```
[----------] Global test environment tear-down
[==========] 419 tests from 37 test cases ran. (5588 ms total)
[  PASSED  ] 418 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestType.testCorruptNestType
```

According to the test coverage, we expect a valid `ParseError` here and this PR breaks the existing behavior.
```
c++/src/TypeImpl.cc:        throw ParseError("Illegal LIST type that doesn't contain one subtype");
```

Could you revise this PR not to break the existing test coverage? In addition, could you add additional test coverage for your case?

File: c++/src/TypeImpl.cc [hunk 2]
```diff
@@ -24,9 +24,9 @@
 #include <sstream>
 
 namespace orc {
-
-  Type::~Type() {
-    // PASS
+  
+   Type::~Type() {
+   // PASS
```
Comment (dongjoon-hyun) [inline c++/src/TypeImpl.cc:29]: These 3-line changes looks wrong. Could you recover to the original code?

File: c++/src/TypeImpl.cc [hunk 3]
```diff
@@ -454,6 +454,7 @@ namespace orc {
         throw ParseError("Illegal MAP type that doesn't contain two subtypes");
       if (type.kind() == proto::Type_Kind_UNION && type.subtypes_size() == 0)
         throw ParseError("Illegal UNION type that doesn't contain any subtypes");
+
```
Comment (dongjoon-hyun) [inline c++/src/TypeImpl.cc:457]: We usually don't mix the bug fix and a style fix in a single PR. Please remove this redundant style change from this PR.

File: c++/src/TypeImpl.cc [hunk 4]
```diff
@@ -465,6 +466,8 @@ namespace orc {
     case proto::Type_Kind_STRUCT: {
       TypeImpl* result = new TypeImpl(STRUCT);
       ret = std::unique_ptr<Type>(result);
+     if (type.subtypes_size() > type.fieldnames_size())
```
Comment (dongjoon-hyun) [inline c++/src/TypeImpl.cc:469]: Could you follow the coding style? This new addition has a wrong indentation.

File: c++/test/TestType.cc [hunk 5]
```diff
@@ -404,6 +404,21 @@ namespace orc {
...
+    structType.set_kind(proto::Type_Kind_STRUCT);
+    structType.add_subtypes(0);  // construct a loop back to root
+    structType.add_fieldnames("root");
+    illStructType.add_subtypes(1);
+    illStructType.add_fieldnames("f1");
+    illStructType.add_subtypes(2);
+    *(footer.add_types()) = illStructType;
+    *(footer.add_types()) = structType;
+    testCorruptHelper(illStructType, footer,
+        "Illegal STRUCT type that contains less fieldnames than subtypes");
```
Comment (dongjoon-hyun) [inline c++/test/TestType.cc:420]: - Thank you for adding a new test coverage.
- And, please remove the redundant empty line 421.

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for updates. I filed an official Apache ORC JIRA issue, ORC-1101.

**Comment by dongjoon-hyun** [comment]
cc @wgtmac , @williamhyun , @stiga-huang

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to main for Apache ORC 1.8.

**Comment by dongjoon-hyun** [comment]
Thank you, @HeenaBansal2009 .
Do you have an Apache JIRA id? I want to assign ORC-1101 to you.

**Comment by HeenaBansal2009** [comment]
> Thank you, @HeenaBansal2009 .
> Do you have an Apache JIRA id? I want to assign [ORC-1101](https://issues.apache.org/jira/browse/ORC-1101) to you.

Thanks @dongjoon-hyun  for merging the PR.  My apache JIRA username is  :  heenabansal

**Comment by dongjoon-hyun** [comment]
Thanks. I added you to the Apache ORC contributor group and assigned ORC-1101 to you, @HeenaBansal2009 .
Welcome to the Apache ORC community.

**Comment by HeenaBansal2009** [comment]
> Thanks. I added you to the Apache ORC contributor group and assigned [ORC-1101](https://issues.apache.org/jira/browse/ORC-1101) to you, @HeenaBansal2009 .
> Welcome to the Apache ORC community.



> 

Thank you @dongjoon-hyun. Since the issue is resolved. can I close ORC-1101?

**Comment by HeenaBansal2009** [comment]
Hi @dongjoon-hyun , Do we have a release with this fix?if yes, Please share the release version.

Thanks

**Comment by dongjoon-hyun** [comment]
Hi, @HeenaBansal2009 . As you see in the right sidebar, this is planned for v1.8.0 which is scheduled on September, https://github.com/apache/orc/milestone/2.

Screen Shot 2022-04-19 at 11 39 44 AM
